- title: BarBend
  slug: barbend
  url: https://barbend.com
  feed: https://barbend.com/feed/
- title: Breaking Muscle
  slug: breaking-muscle
  url: https://breakingmuscle.com
  feed: https://breakingmuscle.com/feed/rss
- title: Brute Strength
  slug: brute-strength
  url: http://brutestrengthtraining.com
  feed: https://www.brutestrengthtraining.com/feed/
- title: Box Life Magazine
  slug: box-life-magazine
  url: http://boxlifemagazine.com
  feed: http://boxlifemagazine.com/feed/
- title: BoxRox
  slug: boxrox
  url: https://www.boxrox.com
- title: Box Pro
  slug: box-pro
  url: http://boxpromag.com
  feed: http://boxpromag.com/feed/atom/
- title: CrossFit Journal
  slug: crossfit-journal
  url: https://journal.crossfit.com
- title: CrossFit WODs
  slug: crossfit-wods
  url: https://www.crossfit.com/workout/
- title: CrossFit Games
  slug: crossfit-games
  url: https://games.crossfit.com
#- title: Generation Iron
#  slug: generation-iron
#  url: http://generationiron.com
#  feed: http://generationiron.com/feed/
- title: elitefts
  slug: elitefts
  url: https://www.elitefts.com
  feed: https://www.elitefts.com/feed
- title: Fitness Volt
  slug: fitness-volt
  url: https://fitnessvolt.com
  feed: https://fitnessvolt.com/feed/
- title: Gameplan A
  slug: gameplan-a
  url: https://www.gameplan-a.com
  feed: https://www.gameplan-a.com/feed/
- title: Gizmodo
  slug: gizmodo 
  url: http://gizmodo.com
  feed: http://gizmodo.com/rss
  category: fitness
- title: Greatest
  slug: greatest
  url: https://greatist.com
  url: https://greatist.com/taxonomy/term/1685/feed
- title: Goop
  slug: goop
  url: https://goop.com/wellness/fitness/
  feed: https://goop.com/wellness/fitness/feed/
- title: GQ
  slug: gq-fitness
  url: https://www.gq.com
  feed: https://www.gq.com/feed/rss
  category: Fitness
- title: Health
  slug: health
  url: https://www.health.com/fitness
  feed: http://www.health.com/fitness/feed
- title: Inside The Affiliate
  slug: inside-the-affiliate
  url: http://www.insidetheaffiliate.com
  feed: http://www.insidetheaffiliate.com/blog/atom.xml
- title: Jezebel
  slug: jezebel 
  url: http://jezebel.com
  feed: http://jezebel.com/rss
  category: fitness
- title: Lifehacker
  slug: lifehacker 
  url: http://lifehacker.com
  feed: http://lifehacker.com/rss
  category: fitness
- title: Mark's Daily Apple
  slug: marks-daily-apple
  url: https://www.marksdailyapple.com
  feed: http://www.marksdailyapple.com/feed/
- title: Maxim
  slug: maxim
  url: https://www.maxim.com
  feed: https://www.maxim.com/.rss/full/
  category: "Men's Fitness"
- title: Morning Chalk Up
  slug: morning-chalk-up
  url: https://morningchalkup.com
  feed: https://morningchalkup.com/feed/
- title: NFPT
  slug: nfpt
  url: https://www.nfpt.com/blog/
- title: NPR
  slug: npr
  url: https://www.npr.org/sections/fitness-nutrition/
  feed: https://www.npr.org/rss/rss.php?id=1134
- title: Outside Magazine
  slug: outside
  url: https://www.outsideonline.com
  feed: https://www.outsideonline.com/rss/fitness/rss.xml
#- title: Pop Sugar
#  slug: pop-sugar
#  url: https://www.popsugar.com/fitness/
#  feed: https://www.popsugar.com/fitness/feed
- title: Tier Three Tactical
  slug: tier-three-tactical
  url: http://www.tierthreetactical.com
- title: Science Daily
  slug: science-daily
  url: https://www.sciencedaily.com/news/health_medicine/fitness/
  feed: https://www.sciencedaily.com/rss/health_medicine/fitness.xml
- title: Self
  slug: self-fitness
  url: https://www.self.com
  feed: https://www.self.com/feed/rss
  category: Fitness
- title: The Barbell Spin
  slug: the-barbell-spin
  url: http://thebarbellspin.com
  feed: http://thebarbellspin.com/feed/
- title: The Box
  slug: the-box
  url: https://www.theboxmag.com
- title: The PTDC 
  slug: the-ptdc
  url: https://www.theptdc.com
  feed: https://www.theptdc.com/feed/
- title: The Rx Review
  slug: the-rx-review
  url: http://therxreview.com
  feed: http://therxreview.com/feed/rss/
- title: T Nation
  slug: t-nation
  url: https://www.t-nation.com
- title: The Yoga Journal
  slug: yoga-journal
  url: https://www.yogajournal.com
  feed: https://www.yogajournal.com/.rss/full/